name: HTML5 - Daily Staging Deployment

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./platforms/html5

      - name: Build project
        run: npm run build:staging
        working-directory: ./platforms/html5

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: "swag-sdk"
          AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: "https://sfo3.digitaloceanspaces.com"
          
      - name: Clear Cloudflare Cache
        env:
          CF_TOKEN: ${{ secrets.CF_TOKEN }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${CF_ZONE_ID}/purge_cache" \
                -H "Authorization: Bearer ${CF_TOKEN}" \
                -H "Content-Type: application/json" \
                --data '{"files":["https://swagapi.shockwave.com/v5/staging/dist/swag-api.js", "https://swagapi.shockwave.com/v5/staging/dist/swag-api.css"]}'
